from infra.Controllers.ProcessoController import ProcessoController
from infra.Controllers.MotivoController import MotivoController
from infra.Controllers.ParteController import ParteController
from infra.Controllers.AudienciaController import AudienciaController
from infra.Models.LuanParte import LuanParte

